export const businessConfig = {
  brand: {
    name: 'NISHA TWO-WHEELER WORKSHOP',
    tagline: 'Precision Service. Reliable Performance.',
    supportingCopy: 'Professional motorcycle service, repair and maintenance built around your ride.',
  },
  contact: {
    phone: '9080949422',
    address: 'Araikulam near bridge, Tirunelveli',
    pincode: '627415',
    whatsapp: 'Hi Nisha Two-Wheeler Workshop, I would like to book a bike service.',
  },
  hours: {
    monday: '9:00 AM - 10:00 PM',
    tuesday: '9:00 AM - 10:00 PM',
    wednesday: '9:00 AM - 10:00 PM',
    thursday: '9:00 AM - 10:00 PM',
    friday: '9:00 AM - 10:00 PM',
    saturday: '9:00 AM - 10:00 PM',
    sunday: 'Closed',
  },
  services: [
    {
      id: 1,
      number: '01',
      titleEn: 'General Service',
      titleTa: 'பொது சேவை',
      descriptionEn: 'Routine inspection, oil replacement, chain check and overall maintenance.',
      descriptionTa: 'வழக்கமான ஆய்வு, எண்ணெய் மாற்றம், சங்கிலி சோதனை மற்றும் ஒட்டுமொத்த பராமரிப்பு.',
    },
    {
      id: 2,
      number: '02',
      titleEn: 'Engine Service',
      titleTa: 'இயந்திர சேவை',
      descriptionEn: 'Engine inspection, diagnosis and repair.',
      descriptionTa: 'இயந்திர ஆய்வு, நோய் கண்டறிதல் மற்றும் பழுது சரிசெய்தல்.',
    },
    {
      id: 3,
      number: '03',
      titleEn: 'Brake Service',
      titleTa: 'பிரேக் சேவை',
      descriptionEn: 'Brake inspection, adjustment and component replacement.',
      descriptionTa: 'பிரேக் ஆய்வு, சரிசெய்தல் மற்றும் கூறு மாற்றம்.',
    },
    {
      id: 4,
      number: '04',
      titleEn: 'Electrical Service',
      titleTa: 'மின்சார சேவை',
      descriptionEn: 'Battery, lighting, wiring and starting-system diagnostics.',
      descriptionTa: 'பேட்டரி, வெளிச்சம், கம்பி மற்றும் தொடக்க அமைப்பு நோய் கண்டறிதல்.',
    },
    {
      id: 5,
      number: '05',
      titleEn: 'Tyre & Wheel',
      titleTa: 'டயர் மற்றும் சக்கரம்',
      descriptionEn: 'Tyre replacement, puncture repair and wheel inspection.',
      descriptionTa: 'டயர் மாற்றம், பஞ்சர் சரிசெய்தல் மற்றும் சக்கர ஆய்வு.',
    },
    {
      id: 6,
      number: '06',
      titleEn: 'Chain & Drive',
      titleTa: 'சங்கிலி மற்றும் இயக்கம்',
      descriptionEn: 'Chain cleaning, lubrication, adjustment and maintenance.',
      descriptionTa: 'சங்கிலி சுத்தம், எண்ணெய் பூசுதல், சரிசெய்தல் மற்றும் பராமரிப்பு.',
    },
  ],
  packages: [
    {
      id: 1,
      titleEn: 'BASIC',
      titleTa: 'அடிப்படை',
      descriptionEn: 'Routine maintenance essentials.',
      descriptionTa: 'வழக்கமான பராமரிப்பு அத்தியாவசியங்கள்.',
      priceEn: 'Starting from ₹2,500',
      priceTa: '₹2,500 இலிருந்து தொடங்கி',
    },
    {
      id: 2,
      titleEn: 'STANDARD',
      titleTa: 'தரநிலை',
      descriptionEn: 'Complete periodic service.',
      descriptionTa: 'முழு கால சேவை.',
      priceEn: 'Starting from ₹5,000',
      priceTa: '₹5,000 இலிருந்து தொடங்கி',
    },
    {
      id: 3,
      titleEn: 'PREMIUM',
      titleTa: 'பிரீமியம்',
      descriptionEn: 'Comprehensive motorcycle inspection and maintenance.',
      descriptionTa: 'விரிவான மோட்டார் சைக்கிள் ஆய்வு மற்றும் பராமரிப்பு.',
      priceEn: 'Starting from ₹10,000',
      priceTa: '₹10,000 இலிருந்து தொடங்கி',
    },
  ],
  brands: [
    'Hero',
    'Honda',
    'TVS',
    'Yamaha',
    'Bajaj',
    'Royal Enfield',
    'Suzuki',
    'KTM',
  ],
  gallery: [
    {
      id: 1,
      category: 'Workshop',
      imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a1/Hochgurgl-Top_Mountain_Motorcycle_Museum-workshop-01ASD.jpg/960px-Hochgurgl-Top_Mountain_Motorcycle_Museum-workshop-01ASD.jpg',
      altEn: 'Premium motorcycle workshop interior',
      altTa: 'பிரீமியம் மோட்டார் சைக்கிள் பணிஅறை',
    },
    {
      id: 2,
      category: 'Service',
      imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/DFC_4703_A_mechanic_works_on_a_motorcycle_engine_on_the_workshop_floor_focused_on_repairing_the_bike_amid_tools_and_parts.jpg/960px-DFC_4703_A_mechanic_works_on_a_motorcycle_engine_on_the_workshop_floor_focused_on_repairing_the_bike_amid_tools_and_parts.jpg',
      altEn: 'Mechanic servicing motorcycle',
      altTa: 'மெக்கானிக் மோட்டார் சைக்கிள் சேவை',
    },
    {
      id: 3,
      category: 'Repairs',
      imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/11/Local_Mechanic_Repairing_a_Motorcycle_Rubber_with_Traditional_Fire.jpg/960px-Local_Mechanic_Repairing_a_Motorcycle_Rubber_with_Traditional_Fire.jpg',
      altEn: 'Close-up engine work',
      altTa: 'இயந்திர பணி விரிவாக',
    },
    {
      id: 4,
      category: 'Bikes',
      imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Ducati_900_Mill_Street_downtown_Littleton_NH_June_2016.jpg/960px-Ducati_900_Mill_Street_downtown_Littleton_NH_June_2016.jpg',
      altEn: 'Premium motorcycle display',
      altTa: 'பிரீமியம் மோட்டார் சைக்கிள் காட்சி',
    },
    {
      id: 5,
      category: 'Mechanics',
      imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/Mekanik_motor_-_motorcycle_mechanic.jpg/960px-Mekanik_motor_-_motorcycle_mechanic.jpg',
      altEn: 'Skilled mechanics at work',
      altTa: 'திறமையான தொழில்நுட்பர்கள் வேலை செய்கின்றனர்',
    },
    {
      id: 6,
      category: 'Workshop',
      imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Suzuki_GSX-R150_-_Indonesia_International_Motor_Show_2017_-_April_30_2017.jpg/960px-Suzuki_GSX-R150_-_Indonesia_International_Motor_Show_2017_-_April_30_2017.jpg',
      altEn: 'Motorcycle maintenance station',
      altTa: 'மோட்டார் சைக்கிள் பராமரிப்பு நிலையம்',
    },
  ],
  testimonials: [
    {
      id: 1,
      nameEn: '[Example Testimonial]',
      nameTa: '[உதாரண சாட்சியம்]',
      bikeEn: 'Hero Passion Pro',
      bikeTa: 'Hero Passion Pro',
      reviewEn: 'Great service experience. The team explained the issue clearly and completed the work professionally. Would definitely recommend!',
      reviewTa: 'சிறந்த சேவை அனுபவம். குழு சிக்கலை தெளிவாக விளக்கி வேலையை தொழில்முறையாக முடித்தது. நிச்சயமாக பரிந்துரைப்பேன்!',
      rating: 5,
    },
    {
      id: 2,
      nameEn: '[Example Testimonial]',
      nameTa: '[உதாரண சாட்சியம்]',
      bikeEn: 'Honda CB Shine',
      bikeTa: 'Honda CB Shine',
      reviewEn: 'Transparent pricing and honest communication. They fixed the issue quickly without unnecessary work. Very satisfied with the service.',
      reviewTa: 'தெளிவான விலை மற்றும் நேர்மையான தொடர்பு. அவர்கள் தேவையற்ற வேலை இல்லாமல் விரைவாக சிக்கலை சரிசெய்தனர். சேவையில் மிகவும் திருப்தி.',
      rating: 5,
    },
    {
      id: 3,
      nameEn: '[Example Testimonial]',
      nameTa: '[உதாரண சாட்சியம்]',
      bikeEn: 'TVS Apache RTR',
      bikeTa: 'TVS Apache RTR',
      reviewEn: 'Professional mechanics who know their work. The quality of service is excellent and the workshop is clean and well-maintained.',
      reviewTa: 'தங்கள் வேலையை நன்கு அறிந்த தொழில்முறை மெக்கானிக்குகள். சேவையின் தரம் சிறந்தது மற்றும் பணிஅறை சுத்தமாகவும் நன்கு பராமரிக்கப்படுகிறது.',
      rating: 5,
    },
  ],
  whyChooseUs: [
    {
      number: '01',
      titleEn: 'Experienced Mechanics',
      titleTa: 'அனுபவமுள்ள மெக்கானிக்குகள்',
    },
    {
      number: '02',
      titleEn: 'Transparent Pricing',
      titleTa: 'தெளிவான விலை',
    },
    {
      number: '03',
      titleEn: 'Quality Parts',
      titleTa: 'தரமான பாகங்கள்',
    },
    {
      number: '04',
      titleEn: 'Detailed Inspection',
      titleTa: 'விரிவான ஆய்வு',
    },
    {
      number: '05',
      titleEn: 'Reliable Service',
      titleTa: 'நம்பகமான சேவை',
    },
    {
      number: '06',
      titleEn: 'Customer First',
      titleTa: 'வாடிக்கையாளர் முதல்',
    },
  ],
  processSteps: [
    {
      number: '01',
      titleEn: 'INSPECT',
      titleTa: 'ஆய்வு செய்க',
      descriptionEn: 'We understand the issue and inspect the motorcycle thoroughly.',
      descriptionTa: 'சிக்கலை புரிந்து கொண்டு மோட்டார் சைக்கிளை முழுமையாக ஆய்வு செய்கிறோம்.',
    },
    {
      number: '02',
      titleEn: 'DIAGNOSE',
      titleTa: 'நோய் கண்டறியல்',
      descriptionEn: 'We identify the required service or repair work.',
      descriptionTa: 'தேவையான சேவை அல்லது பழுதுதிருத்தத்தை கண்டறிகிறோம்.',
    },
    {
      number: '03',
      titleEn: 'SERVICE',
      titleTa: 'சேவை',
      descriptionEn: 'Our mechanics carry out the required work with precision.',
      descriptionTa: 'எங்கள் மெக்கானிக்குகள் தேவையான வேலையை துல்லியமாக செய்கிறார்கள்.',
    },
    {
      number: '04',
      titleEn: 'CHECK',
      titleTa: 'சரிபார்ப்பு',
      descriptionEn: 'The motorcycle receives a final quality inspection.',
      descriptionTa: 'மோட்டார் சைக்கிள் இறுதி தர ஆய்வைப் பெறுகிறது.',
    },
    {
      number: '05',
      titleEn: 'READY',
      titleTa: 'தயாராக',
      descriptionEn: 'Your bike is ready for the road.',
      descriptionTa: 'உங்கள் பைக் சாலைக்கு தயாராக உள்ளது.',
    },
  ],
  about: {
    titleEn: 'BUILT ON TRUST.\nDRIVEN BY CRAFT.',
    titleTa: 'நம்பிக்கையின் மீது கட்டப்பட்டது.\nகைத்திறத்தால் இயக்கப்படுகிறது.',
    descriptionEn: 'Nisha Two-Wheeler Workshop is focused on dependable motorcycle service, honest communication and careful workmanship. We believe every ride deserves the best care.',
    descriptionTa: 'Nisha Two-Wheeler Workshop நம்பகமான மோட்டார் சைக்கிள் சேவை, நேர்மையான தொடர்பு மற்றும் கவனமான கைத்திறனில் கவனம் செலுத்துகிறது.',
    stats: [
      {
        numberEn: '10+',
        numberTa: '10+',
        labelEn: 'Years Experience',
        labelTa: 'ஆண்டுகளின் அனுபவம்',
      },
      {
        numberEn: '1000+',
        numberTa: '1000+',
        labelEn: 'Bikes Serviced',
        labelTa: 'சேவை செய்யப்பட்ட பைக்குகள்',
      },
      {
        numberEn: '100%',
        numberTa: '100%',
        labelEn: 'Customer Focus',
        labelTa: 'வாடிக்கையாளர் கவனம்',
      },
    ],
  },
  socialLinks: {
    instagram: '#',
    facebook: '#',
    googleBusiness: '#',
  },
};